export enum DefenderActionType {
    DROP_TOFU = "DROP_TOFU",
    DROP_CRACKERS = "DROP_CRACKERS",
    DROP_WORMS = "DROP_WORMS",
    PICKUP_TOFU = "PICKUP_TOFU",
    PICKUP_CRACKERS = "PICKUP_CRACKERS",
    PICKUP_WORMS = "PICKUP_WORMS",
    PICKUP_LOGS = "PICKUP_LOGS",
    REPAIR_TRAP = "REPAIR_TRAP",
}